### ISSUE TITLE
Brief explanation of each parameter that the API can fetch should be added to README

### ISSUE THREAD

**Issue by Milind220** [Milind220/Ozone#30]
Ozone can currently fetch the following parameters (taken from the Ozone class): 

`[
        "aqi",
        "pm25",
        "pm10",
        "o3",
        "co",
        "no2",
        "so2",
        "dew",
        "h",
        "p",
        "t",
        "w",
        "wg",
    ]`

Some of these parameters, such as 'aqi' are pretty obvious in meaning, but others, such as 'h' , 'w', 'wg', 't' are not easily understood.

It would be excellent to have a short section explaining each parameter briefly in the README, perhaps under the code examples.

You can check the WAQI API website and see if they have the meanings there, or otherwise a google search should prove useful.

**Comment by Milind220** [comment]
Hold my beer, I got this

**Comment by Milind220** [comment]
I was just testing our new bot out! Feel free to take this :)

**Comment by kristinamancini** [comment]
Hold my beer, I got this

**Comment by kristinamancini** [comment]
I have gathered explanations for each parameter, however I am having trouble finding the meaning of the parameter ‘wg’. I searched for the meaning on the WAQI website and others but cannot seem to find it. 

Here is what I have so far:

 * aqi: air quality index, a measurement of air quality that tells you how clean or polluted the air is
 * pm25: fine particulate matter, a measure of 2.5 micrometers or smaller particles in the air
 * pm10: respirable particulate matter, a measure of 10 micrometers or smaller particles in the air
 * o3: a measure of ground level ozone concentrations in the air
 * co: a measure of carbon monoxide concentrations in the air
 * no2: a measure of nitrogen dioxide concentrations in the air
 * so2: a measure of sulfur dioxide concentrations in the air
 * dew: dew point, the temperature the air needs to be cooled to in order to reach 100% relative humidity
 * h: relative humidity, a measure of moisture in the atmosphere
 * p: atmospheric pressure, a measure of the weight of atoms and molecules that make up the layers in the atmosphere
 * t: temperature, a measure of thermal energy in one or a combined substance at a given time
 * w: wind speed, a measure of air in motion
 * wg:

Sources used: 
[WAQI](https://aqicn.org)
[United States Environmental Protection Agency](https://www.epa.gov/) 
[National Weather Service](https://www.weather.gov/)

**Comment by Milind220** [comment]
@kristinamancini That's awesome! 

Don't worry about the last parameter 'wg'. We can always merge in what you got right now and add the line for 'wg' when someone manages to find it.

You can go ahead and make your PR if you're done making changes! Thanks a lot.
