### ISSUE TITLE
Add a link to the versioning model in the README and the GitHub branching model in the CONTRIBUTING file

### ISSUE THREAD

**Issue by Milind220** [Milind220/Ozone#40]
The versioning model explains how Ozone uses semantic versioning to increment it's release version number.
The GitHub branching model explains how Ozone branches are created, and what purpose each one serves.

Both are currently covered in Ozone's discussions forum ([versioning](https://github.com/Milind220/Ozone/discussions/26) and [branching-model](https://github.com/Milind220/Ozone/discussions/24))

* Add a section in the README near the bottom about 'Semantic Versioning System' and refer to the link in the discussion.
* Add a section in the contributing file near the bottom called 'Github Branching Model' and refer to the link in the discussion.

Maybe add small descriptions of both.

**Comment by kristinamancini** [comment]
Hi! I’m looking to contribute to open source projects, and I was wondering if I could be assigned this issue. Thanks!

**Comment by Milind220** [comment]
@kristinamancini Hi! Sure thing, let me know if you need help with any part of it

**Comment by kristinamancini** [comment]
For a section about ‘Semantic Versioning System’, would it be best to put it above the ‘Contributing and submitting Pull Requests’ section in the README.md? And similarly, for a ‘GitHub Branching Model’ section, would it be best to put it under the Style Guides section in the contributing file?

**Comment by Sam-damn** [comment]
hey @kristinamancini i think it is best to do it like @Milind220 mentioned, at the bottom of the file so that means under the 
Style Guides , because if you think about it, What any new contributor would want to see first is the Pull request section since it is a detailed step by step guide, and then next they will want information on how to style their commits and format their code so the Style Guide comes next, and then if they are interested in anymore information they can refer to the ‘GitHub Branching Model’ and ‘Semantic Versioning System’ that come next in that order :)

**Comment by kristinamancini** [comment]
Got it, thank you!
