### ISSUE TITLE
MyPy flags a type incompatibility in line 436 of Ozone.py. This is in the get_specific_parameter method

### ISSUE THREAD

**Issue by Milind220** [Milind220/Ozone#79]
### Here's the warning that's displayed:

Argument of type "Series[Unknown]" cannot be assigned to parameter "x" of type "SupportsFloat | SupportsIndex | str | bytes |

### This is the line of code that causes this:
```python
result = float(row[air_param])
```
### Possible explanation
Here, row is a Pandas dataframe, and air_param is a column in it

This warning, if I understand correctly, is basically indicating that MyPy has no guarantee that the value stored in that cell is a number. Due to this, it's not comfortable with us type casting it as a float while assigning it to result.

## Possible solution

Better implementation of `get_specific_parameter` method. This method currently creates an entire dataframe by calling `get_city_air`, when all it requires is a single number. A more lightweight method of implementing it would be to make an API call, and then get the required parameter directly from the JSON response, and return it from there.

**Comment by lahdjirayhan** [comment]
Strange, mypy does not complain about it to me (I bet it's something on my end, though). Good catch either way.

---

I don't have anything to say about fixing the mypy warning. However, I have something to say about the possible solution.

I changed the implementation of `get_specific_parameter` method to this one [in this commit](https://github.com/Milind220/Ozone/pull/70/commits/999326bf235340ab1c8ff6b8898ac3d093afeea3) because I find it an unnecessary duplication of code that's already in `get_city_air`. Why write this bit of logic twice:

1. Bulilding a URL.
1. Making request (handled by Ozone via `_make_api_request`)
1. Checking error code (handled by Ozone via `_check_status_code`)
1. Checking if the JSON returned is truly OK (I added this check in [this commit](https://github.com/Milind220/Ozone/pull/70/commits/3b3482cda7096c083311f04e836b8b0d195fbc05) to handle cities without AQI data. It will also be needed in `get_specific_parameter`)
1. Parsing the data (handled by Ozone via `_parse_data`)
1. And finally, take the intended parameter.

I don't think this duplication of logic should be maintained.

If `get_city_parameter` and `get_specific_parameter` should not call one another, I think the better solution is to refactor the implementation so that the bulk of steps up to step 5 above is handled in a private method. `get_specific_parameter` can take the intended air quality parameter while `get_city_air` convert all of the parsed results into a dataframe row.

What do you think? @Milind220

**Comment by lahdjirayhan** [comment]
Also after I think about it, any further fixes to `get_city_air` will also need to be applied to `get_specific_parameter`, since basically they're calling the same API URL endpoint and should get roughly the same result. I'm inclined to think refactoring is the best way to go.

**Comment by Sam-damn** [comment]
@lahdjirayhan i agree with line of reasoning of grouping steps from 1 to 5 in a private method for it to be reused to reduce the redundancy in both methods, would you like to hold the beer for this one ?

**Comment by Milind220** [comment]
@lahdjirayhan Definitely agree with you there - a private method to cover that functionality would be ideal and much cleaner than repeating the code.

@Sam-damn ahahaha I love that line "would you like to hold the beer for this one?" - Great stuff hahaha

**Comment by Milind220** [comment]
This issue is actually only a symptom of the actual problem that you've pointed out. Let's close this issue and create a new one to address the need for refactoring that section of code.
